
services:
  db:
    image: postgres:17
    env_file: config/.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: docker/dev/api/Dockerfile
    command: bash ./run_dev.sh
    env_file: config/.env
    ports:
      - "8000:8000"
    volumes:
      - "./backend:/backend/"
      - django_media:/media
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: docker/dev/frontend/Dockerfile
    command: npm run dev -- --host
    volumes:
      - "./frontend:/frontend/"
      - /frontend/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - api



volumes:
  pgdata:
  django_media:

