
services:
  db:
    image: postgres:17
    env_file: config/.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: docker\dev\api\Dockerfile
    command: bash ./run_dev.sh
    env_file: config/.env
    ports:
      - "8000:8000"
    volumes:
      - "./backend:/src/"
      - django_media:/media
    depends_on:
      - db
    restart: always


volumes:
  pgdata:
  django_media:

