POST_STATUS_PUBLISHED = "Published"
POST_STATUS_DRAFT = "Draft"

ADMINISTRATOR_ROLE_ID = 1
AUTHOR_ROLE_ID = 2

AUTHOR_ROLES = [ADMINISTRATOR_ROLE_ID, AUTHOR_ROLE_ID]

TRUNCATE_TEXT_IN_POST_LIST_TO_WORDS = 60
