# Generated by Django 5.2 on 2025-04-14 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("blogs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("alt", models.CharField(blank=True, help_text="Описание изображения", max_length=100, null=True)),
                ("image", models.ImageField(help_text="Изображение", upload_to="blog_images")),
                (
                    "blog",
                    models.ForeignKey(
                        help_text="Идентификатор блога в который было загружено изображение",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blogs.blog",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=2,
                        help_text="Идентификатор пользователя загрузившего изображение",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
