# Generated by Django 5.2 on 2025-04-14 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("blogs", "0001_initial"),
        ("tags", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(help_text="Имя поста в ссылке", max_length=270)),
                ("title", models.CharField(help_text="Заголовок поста", max_length=255)),
                ("content", models.TextField(help_text="Содержимое поста")),
                (
                    "status",
                    models.CharField(choices=[("Draft", "Черновик"), ("Published", "Опубликованный")], max_length=9),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "blog",
                    models.ForeignKey(
                        help_text="Идентификатор блога",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="blogs.blog",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=2,
                        help_text="Идентификатор пользователя",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        help_text="Идентификатор Поста", on_delete=django.db.models.deletion.CASCADE, to="posts.post"
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        help_text="Идентификатор тега", on_delete=django.db.models.deletion.CASCADE, to="tags.tag"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                help_text="Теги", related_name="posts", through="posts.PostTag", to="tags.tag"
            ),
        ),
    ]
