# Generated by Django 5.2 on 2025-04-15 11:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_blog_created_at"),
        ("posts", "0001_initial"),
        ("tags", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="post",
            constraint=models.UniqueConstraint(fields=("blog", "slug"), name="unique_blog_post_slug"),
        ),
    ]
