# Generated by Django 5.2 on 2025-04-15 12:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_blog_created_at"),
        ("posts", "0002_post_unique_blog_post_slug"),
        ("tags", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="post",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ("Draft", "Published"))),
                name="check_valid_post_status",
                violation_error_message="Статус должен быть 'Draft' или 'Published'",
            ),
        ),
    ]
