# Generated by Django 5.2 on 2025-04-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Название тега", max_length=30)),
                ("slug", models.SlugField(help_text="Слаг", max_length=40)),
            ],
        ),
    ]
