# Generated by Django 5.2 on 2025-04-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(help_text="Название тега", max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(help_text="Слаг", max_length=40, unique=True),
        ),
    ]
