# Generated by Django 5.2 on 2025-04-15 15:11

from django.db import migrations, models

from roles.models import Role


def create_default_roles(apps, schema_editor):
    Role.objects.create(id=1, name="Администратор")
    Role.objects.create(id=2, name="Автор")


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Название роли")),
            ],
        ),
        migrations.RunPython(create_default_roles),
    ]
