# Generated by Django 5.2 on 2025-04-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(help_text="Название роли", max_length=15),
        ),
    ]
