# Generated by Django 5.2 on 2025-04-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0002_comment_created_at_comment_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="comment",
            name="edited",
            field=models.BooleanField(default=False),
        ),
    ]
