# Generated by Django 5.2 on 2025-04-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                ("bio", models.TextField(blank=True, help_text="О себе", null=True)),
                ("email", models.EmailField(help_text="Email", max_length=254, unique=True)),
                ("username", models.CharField(help_text="Имя пользователя", max_length=30, unique=True)),
                ("first_name", models.CharField(blank=True, help_text="Имя", max_length=30)),
                ("last_name", models.CharField(blank=True, help_text="Фамилия", max_length=30)),
                ("is_active", models.BooleanField(default=True, help_text="Пользователь активен")),
                ("is_staff", models.BooleanField(default=False, help_text="Персонал")),
                ("is_superuser", models.BooleanField(default=False, help_text="Суперпользователь")),
                ("date_joined", models.DateTimeField(auto_now_add=True, help_text="Дата регистрации")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
