# Generated by Django 5.2 on 2025-04-14 11:28
from django.contrib.auth import get_user_model
from django.db import migrations


def create_removed_user(apps, schema_editor):
    User = get_user_model()
    User.objects.create(
        id=2,
        email="removed_user@mydomain.com",
        username="removed_user",
        first_name="Удаленный",
        last_name="Пользователь",
        is_active=False,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_removed_user)]
