# Generated by Django 5.2 on 2025-04-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_add_removed_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, help_text="Аватар пользователя", null=True, upload_to="users"),
        ),
    ]
